version: '3.3'

services:
  postgres:
    image: postgres:11-alpine
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    env_file: .env
    ports:
      - '5432:5432'
    networks:
      - 'lovelystay'

  node:
    build:
      context: .
    env_file: .env
    volumes:
      - ./:/app
    ports:
      - '8080:8080'
    networks:
      - 'lovelystay'

networks:
  lovelystay:
    name: lovelystay
